config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoveSquared</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <p class='m-0 ml-5'>SUSAN HUM</p>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active d-flex align-items-center">
                <%= link_to 'Home', root_path %>
              </li>
              <li class="nav-item d-flex align-items-center">
                <%= link_to "About", about_path %>
              </li>
              <li class="nav-item dropdown">
                <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
                </div>
              </li>
              <!--li class="nav-item"-->
              <!--/li-->
          </ul>
        </div>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/contact.html.erb
<h1>Contact page</h1>

app/views/pages/home.html.erb
<div id='backdrop'>
  <div class='banner'>
    <div class='hero-text'>
      <p class='first-line'>How to be happy in life?</p>
      <p class='second-line'>Building great relationships leads to an amazing life!</p>
    </div>
  </div>
  <div id='overlay'>
    <section id='second-box'>
      <h2  class='titles text-center'>Are you facing relationship problems?</h2>
      <div class='problems'>
        <div class='problem-box'>
          <h6 class='numbers'>01.</h6>
          <h4 class='problem-titles'>Couple Problems</h4>
          <p class='description'>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <%= link_to "Let's talk", contact_path, class:'links' %>
        </div>
        <div class='problem-box'>
          <h6 class='numbers'>02.</h6>
          <h4 class='problem-titles'>Parent-Child Problems</h4>
          <p class='description'>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <%= link_to "Let's talk", contact_path, class:'links' %>
        </div>
        <div class='problem-box'>
          <h6 class='numbers'>03.</h6>
          <h4 class='problem-titles'>Commitment Issues</h4>
          <p class='description'>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <%= link_to "Let's talk", contact_path, class:'links' %>
        </div>
        <div class='problem-box'>
          <h6 class='numbers'>04.</h6>
          <h4 class='problem-titles'>Family Issues</h4>
          <p class='description'>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <%= link_to "Let's talk", contact_path, class:'links' %>
        </div>
      </div>
      <div class='seperator'></div>
    </section>
    <div class='divider-element'></div>
    <section class='solutions'>
      <h2 class='titles text-center'>How can I help you be happier?</h2>
      <div class='solution-container'>
        <div class='solution-box'></div>
        <div class='solution-box'></div>
        <div class='solution-box'></div>
      </div>
    </section>
    <div class='divider-element'></div>
    <section>
      <div class='transparent-box'>
        <div id='transparent-box-text'>
          <h3>An amazing relationship leads to ut labore et dolore magnam etiam.</h3>
          <h6>Susan Hum</h6>
        </div>
        <div id='worker'>
          <%= image_tag('worker.png', :class => 'worker-img') %>
        </div>
        <div id='about'>
          <h3>About Me</h3>
          <h6>I’m an NLP Certified Relationship Coach eius modi tempora incidunt.</h6>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
          <%= link_to 'Read More', about_path, class:'btn about-link' %>
        </div>
      </div>
    </section>
    <section id='clients'>
      <div class='seperator'></div>
      <h4>Happy Clients</h4>
      <div class='solution-container'>
        <div class='solution-box reviews'></div>
        <div class='solution-box reviews'></div>
        <div class='solution-box reviews'></div>
      </div>
    </section>
  </div>
</div>